import type { Metadata } from "next";
import { Barlow_Condensed } from "next/font/google";
import "./globals.css";
import ResponsiveNav from "./components/Navigation/ResponsiveNav";

const barlow = Barlow_Condensed({
  weight: [
    "100", "200", "300", "400", "500", "600", "700", "800", "900"
  ],
  subsets: ["latin"]
});

export const metadata: Metadata = {
  title: "Burger Website",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={barlow.className}>
      <ResponsiveNav/>
        {children}
      </body>
    </html>
  );
}
